name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # O branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Ajuste para a versão do Python que você está usando

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest test_app.py  # Ajuste conforme necessário

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HRKU-d6225da8-022c-4edc-8cae-2f79c8541783 }}
      run: |
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main
