name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # ou o seu branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # ou a versão do Python que seu projeto está usando

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Verifique se as dependências estão listadas em requirements.txt

    - name: Run Tests
      run: |
        pytest test_app.py  # Ajuste o comando para executar seus testes

    - name: Deploy
      if: github.ref == 'refs/heads/main'  # Apenas implanta no branch principal
      run: |
        # Comandos para implantar sua aplicação
        # Exemplo se você estiver usando Heroku:
        # heroku git:remote -a seu-app-heroku
        # git push heroku main

        # Se você estiver usando outro método, substitua pelo seu comando de implantação
